# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
<%# default: &default %>
<%#   adapter: sqlite3 %>
<%#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %1> %>
<%#   timeout: 5000 %>

default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DATABASE_HOST") { "localhost" } %>

development:
  <<: *default
  database: xxx_dev

production:
  <<: *default
  database: xxx_prod

test:
  <<: *default
  database: xxx_test

